Delensing for review
simonsobs/BBPower pull request #20
Opened 2023-04-12 22:20 UTC by damonge

2023-04-12 22:26 UTC, damonge reviewed
@ehertig just a few comments on the examples scripts. It's good to keep them clean because they're helpful when testing the code.

An alternative to my comments below would be if you want to create your own `generate_SO_spectra_with_delensing.py` script.

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +#bpss = {n: Bpass(n,f'examples/data/bandpasses/{n}.txt') for n in band_names}
Can we keep the old path?

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +nbands = 30
Can we keep the old bandpowers?

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +beams = {band_names[i]: b for i, b in enumerate(nc.Simons_Observatory_V3_SA_beams(larr_all)[2:5])} # Add [2:5] for 3 channels only
I guess we don't need this either

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +#_,nell[:,2:],_=nc.Simons_Observatory_V3_SA_noise(sens,knee,ylf,fsky,lmax+1,1)
likewise

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +    #s_d.add_ell_cl(cl_type, n1, n2, leff, bpw_freq_sig[i1, i2, :], window=s_wins)
uncomment this

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +    #s_n.add_ell_cl(cl_type, n1, n2, leff, bpw_freq_noi[i1, i2, :], window=s_wins)
uncomment this

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +#s_d.add_covariance(cov_bpw)
uncomment

2023-04-12 22:26 UTC, damonge commented on examples/generate_SO_spectra.py
> +#s_n.save_fits(prefix_out + "/cls_noise.fits", overwrite=True)
uncomment.

2023-04-12 22:26 UTC, damonge commented on examples/utils.py
> +A_sync_BB = 0. #1.6
I'm fine with this change, but let's use 1.6 instead of 0

2023-04-12 22:26 UTC, damonge commented on examples/utils.py
> +A_dust_BB = 0. #28.
same here, let's make it non-zero

2023-04-12 22:26 UTC, damonge commented on examples/utils.py
> +band_names = ['MF1', 'MF2', 'UHF1'] #['LF1', 'LF2', 'MF1', 'MF2', 'UHF1', 'UHF2']
back to all freqs!

2023-04-12 22:26 UTC, damonge commented on examples/utils.py
> +    #_,dls_cmb_ee,dls_cmb_bb,_=read_camb("./examples/data/camb_lens_nobb.dat", lmax)
let's keep the previous path (or put the file you used into the repo)

2023-04-25 13:10 UTC, kwolz commented on examples/utils.py
> +A_sync_BB = 0. #1.6
Agreed, also 1.6 is the SAT sims' fiducial value, to be preferred over 2.0

2023-04-25 13:10 UTC, kwolz commented on examples/utils.py
> +A_dust_BB = 0. #28.
SAT value is 28

2023-04-25 16:32 UTC, kwolz requested changes
Great work overall! Some minor comments in the source code. 
I agree to David's comments regarding the example scripts, which should be suitable as quick tests of the code.

2023-04-25 16:32 UTC, kwolz commented on bbpower/compsep.py
> +            end = time.time()
I would keep this change (meaning I would keep `end=time.time()` outside the `if` condition, so `end` is defined in all cases (not only for `emcee`).

2023-04-25 16:32 UTC, kwolz commented on bbpower/compsep.py
> +                        else: # Analytically, template & B-modes cross-spectrum is the same as template auto-spectrum
This is probably true; I'm just commenting here to remind myself that this seems nontrivial.

2023-04-25 16:32 UTC, kwolz commented on bbpower/power_specter.py
> +            m = hp.read_map(self.get_input('masks_apodized'), field=i,
Originally the `mask_apodized` file contained a single field for both polarizations, which is why `field=...` was omitted. Setting `field=i` will probably result in an error here if the original fits file is read, which we should avoid. Unless the lensing template requires a different mask (in which case we might think about loading from a different file), I would suggest keeping `field=0` here.

2023-04-25 16:32 UTC, kwolz commented on bbpower/power_summarizer.py
> +        print('Saving mean sims spectra')
Great idea. We could consider making saving the mean spectra optional, but since this wouldn't use up a lot of space I'm all for keeping it.

2025-01-13 15:48 UTC, closed without merging